%YAML 1.2
---
name: '32930_AF_v1'                  # ideally no spaces
gpu: 0                                 # gpu id to process on

dataset: 
  num_chunks: 233620                 # newest nof chunks to parse
  train_ratio: 0.90                    # trainingset ratio
  # For separated test and train data.
  input_train: 'C:\Training_Games_C_Drive\AF-SF Games\AF-SF-Games-v*\' # supports glob
  input_test: 'C:\Training_Games_C_Drive\AF-SF Games\AF-SF-v6_ONLY\'  # supports glob
  # For a one-shot run with all data in one directory.
  #input: 'C:\Training_Games_C_Drive\AF-SF Games\AF-SF-Games-T30_1_29_19_1_27_training-run2-20190127-1917Firsttraining-run2-20190130-0017Last\training-run2*\'

training:
    swa: false
    swa_steps: 25
    swa_max_n: 30
    max_grad_norm: 2
    batch_size: 1024                   # training batch
    num_batch_splits: 2
    test_steps: 1000                    # eval test set values after this many steps
    train_avg_report_steps: 25        # training reports its average values after this many steps.
    total_steps: 18250                  # terminate after these steps
    warmup_steps: 125
    checkpoint_steps: 1000          # optional frequency for checkpointing before finish
    shuffle_size: 100000               # size of the shuffle buffer
    lr_values:                         # list of learning rates
        - 0.002
        - 0.00002
    lr_boundaries:                     # list of boundaries
        - 7300
    policy_loss_weight: 1.0            # weight of policy loss
    value_loss_weight: 1.0            # weight of value loss
    path: 'D:\Leela_Pipeline\networks'          # network storage dir

model:
  filters: 256
  residual_blocks: 20
  #se_ratio: 8
  #policy_channels: 80
...